In [1]:
%matplotlib inline

In [2]:
%load_ext autoreload

In [3]:
%autoreload 2

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import scipy

In [5]:
from ftnmr import *

In [6]:
a = fid(shift=3, B=4.0, T2=10, t_cut=1000)

In [7]:
b = fid(shift=6, B=4.0, T2=10, t_cut=1000)

In [8]:
c = fid(shift=9, B=4.0, T2=10, t_cut=1000)

In [9]:
d = fid(shift=12.8, B=4.0, T2=10, t_cut=1000)

In [10]:
molecules = []

Hydrogens and their frequencies and ratios

In [66]:
from string import ascii_lowercase as asc

In [68]:
a = ''

In [70]:
for i in asc:
    a += i

In [71]:
a

'abcdefghijklmnopqrstuvwxyz'

In [13]:
from scipy.special import binom

In [95]:
a = ('a', 1, 2.3)
b = ('b', 4, 3.4)
c = ('c', 1, 4.5)
A = {
    'a':(1, 2.3),
    'b':(4, 3.3),
    'c':(1, 4.5)}

j1 = ('a', 'b', 3.300)
j2 = ('b', 'c', 3.000)
B = [j1, j2]

In [54]:
C = {a[0]:[] for a in A}

In [64]:
q

KeyError: 1

In [35]:
C[A[1][0]]

[]

In [23]:
for i in A:
    print(i)

('a', 1, 2.3)
('b', 4, 3.4)
('c', 1, 4.5)


In [80]:
A['b'][0]

4

In [96]:
C = {a:[] for a in A}
C

{'a': [], 'b': [], 'c': []}

In [97]:
for k in A:
    for b in B:
         if k in b: C[k].append((b[2], A[b[1]][0]))

C

{'a': [(3.3, 4)], 'b': [(3.3, 4), (3.0, 1)], 'c': [(3.0, 1)]}

In [98]:
F = {a:[] for a in A}
F

{'a': [], 'b': [], 'c': []}

In [ ]:
for k in A:
    F[k].append()

In [101]:
b = C['a']
f_ba = np.array([n*b[0]/2 for n in range(-a[1], a[1] + 1, 2)])

TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

In [40]:
f_ba

array([-1.65,  1.65])

In [41]:
f_bc = np.array([n*j2[2]/2 for n in range(-c[1], c[1] + 1, 2)])

In [42]:
f_bc

array([-1.65,  1.65])

In [36]:
x_ba = [binom(a[1], x)/pow(2,a[1]) for x in range(0, a[1] + 1)]

In [37]:
x_bc = [binom(c[1], x)/pow(2,c[1]) for x in range(0, c[1] + 1)]

In [43]:
x_ba

[0.5, 0.5]

In [44]:
x_bc

[0.5, 0.5]

In [45]:
f = []
for i in f_ba:
    for j in f_bc:
        f.append(i + j)

In [46]:
f

[-3.3, 0.0, 0.0, 3.3]

In [47]:
z = []
for i in x_ba:
    for j in x_bc:
        z.append(j*i)

In [48]:
z

[0.25, 0.25, 0.25, 0.25]

In [195]:
list(np.argsort(f))

[0, 1, 2, 3]

In [196]:
np.sort(f)

array([-3.3,  0. ,  0. ,  3.3])

In [197]:
np.argsort(f)

array([0, 1, 2, 3])

In [199]:
F = np.sort(f)

In [200]:
F

array([-3.3,  0. ,  0. ,  3.3])

In [204]:
z = []
for i in x_ba:
    for j in x_bc:
        z.append(j*i)

In [205]:
z

[0.25, 0.25, 0.25, 0.25]

In [206]:
Z = np.array([z[i] for i in np.argsort(f)])

In [208]:
Z

array([0.25, 0.25, 0.25, 0.25])

In [207]:
sum(Z)

1.0

Molecule construction

In [213]:
a = ('a', 6, 2.3)
b = ('b', 4, 3.4)
c = ('c', 2, 4.5)
A = [a, b, c]

j1 = ('a', 'b', 3.300)
j2 = ('b', 'c', 3.000)
B = [j1, j2]

In [222]:
class molecule():
    def __init__(
        self,
        A: list,
        B: list):
        self.A = A
        self.B = B

In [223]:
a = molecule(A=[1, 2, 3], B=2)

In [230]:
def add(x: int, y: int) -> int:
    return x + y

In [231]:
add(2, 4)

6

In [234]:
num: str = add('bab', 'o')

In [235]:
num

'babo'